apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-plate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: full-plate
  template:
    metadata:
      labels:
        app: full-plate
    spec:
      containers:
      - name: full-plate
        image: full-plate:v1
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"