apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-plate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: full-plate
  template:
    metadata:
      labels:
        app: full-plate
    spec:
      containers:
      - name: full-plate
        image: full-plate:v1
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: full-plate-secret
              key: DATABASE_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: full-plate-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: full-plate-secret
              key: DB_PASSWORD
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: full-plate-secret
              key: DB_HOSTNAME
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: full-plate-secret
              key: DB_NAME
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: full-plate-secret
              key: SECRET_KEY_BASE