version: '2'
services:

  app:
    image: phoenix:latest
    build: .
    command: >
      /bin/sh -c "
      mix deps.get &&
      mix ecto.create &&
      mix ecto.migrate &&
      mix phx.server
      "
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: full_plate_dev
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

