apiVersion: v1
kind: Service
metadata:
  name: full-plate-service
spec:
  type: NodePort
  selector:
    app: full-plate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000